[package]
name = "cowbox"
version = "0.1.0"
edition = "2021"

[dependencies]
cowbox_injection = { path = "../cowbox_injection" }

[target.'cfg(windows)'.dependencies]
detours_sys = { path = "../detours_sys" }

[dev-dependencies]
cowbox_testing = { path = "../cowbox_testing" }
