name: Test
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches: main
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Install Vcpkg dependencies
        if: runner.os == 'Windows'
        run: |
          cargo install cargo-vcpkg
          cargo vcpkg build
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
      - name: Typecheck
        run: cargo check --all-targets --all-features
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run tests
        run: cargo test
