name: Test
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches: main
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
      - name: Install vcpkg dependencies
        if: runner.os == 'Windows'
        run: |
          cargo install cargo-vcpkg
          cargo vcpkg build
      - name: Typecheck
        run: cargo check --all-targets --all-features
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Build dylib
        run: cargo build --release
      - name: Build dylib (Windows x86)
        if: runner.os == 'Windows'
        run: |
          cargo build --release --target i686-pc-windows-msvc
          cp \
            target\release\cowbox.dll \
            target\release\cowbox64.dll
          cp \
            target\i686-pc-windows-msvc\release\cowbox.dll \
            target\release\cowbox32.dll
      - name: Run tests
        run: cargo test
      - name: Run tests (Windows x86)
        if: runner.os == 'Windows'
        run: cargo test --target i686-pc-windows-msvc
